# use the official gcc image, based on debian
image: ubuntu:bionic

build:
  stage: build
  before_script:
     - apt update && apt -y install g++ make autoconf automake 
       libtool gnulib gengetopt zlib1g-dev libboost-dev libboost-filesystem-dev 
       libboost-system-dev libboost-iostreams-dev libboost-test-dev 
       libbamtools-dev
  script:
    - autoreconf -fi
    - ./configure --enable-tests
    - make -j
    - cd tests; make check -j;
  artifacts:
    paths:
      - src/idemuxCPP
      - tests/test_barcode
      - tests/test_demuxer
      - tests/test_parser

#run tests
#test:
#  stage: test
#  script:
#    - tests/test_barcode --log_level=all
#    - tests/test_demuxer --log_level=all
#    - tests/test_parser --log_level=all
